version: '2'

services:
  toycardgameclient:
    image: toycardgameclient
    build:
      context: ./ToyCardGameClient
      dockerfile: Dockerfile

  toycardgameserver:
    image: toycardgameserver
    build:
      context: ./ToyCardGameServer
      dockerfile: Dockerfile